name: build

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: checkout
        uses: actions/checkout@v4

      - name: build deb package
        id: build 
        run: make deb && echo "status=success" >>$GITHUB_OUTPUT && echo "DEB_NAME=$(build/*.deb|xargs basename)" >>$GITHUB_ENV

      - name: artifact
        uses: actions/upload-artifact@v4
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.DEB_NAME }}
          path: build/${{ env.DEB_NAME }}.deb
