name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: checkout
        uses: actions/checkout@v4

      - name: build deb package
        run: make deb
